---
title: "movie 10"
author: "Andrey Sumadic"
date: "2024-02-13"
output: pdf_document
---

```{r }
# Install and load required packages
install.packages("rvest")
install.packages("httr")
install.packages("polite")
```

```{r}

library(rvest)
library(httr)
library(polite)
```

```{r}
# Set up polite scraper
polite::use_manners(save_as = 'polite_scrape.R')
```

```{r}
# Define the URL template
url_template <- 'https://www.imdb.com/title/tt0084787/reviews/_ajax?ref_=undefined&paginationKey=%s'
```

```{r}
# Initialize vectors
movie10Usernames <- character(0)
movie10ReviewerDates <- character(0)
movie10ReviewerContents <- character(0)
movie10Ratings <- character(0)
```

```{r}
# Scrape data from multiple pages
reviews_to_scrape <- 300
pagination_key <- ""
for (page in 1:ceiling(reviews_to_scrape / 25)) {
  session <- bow(sprintf(url_template, pagination_key), user_agent = "Educational")
  
  # Scrape data
  movie10Usernames <- c(movie10Usernames, scrape(session) %>% html_nodes('span.display-name-link') %>% html_text())
  movie10ReviewerDates <- c(movie10ReviewerDates, scrape(session) %>% html_nodes('span.review-date') %>% html_text())
  movie10ReviewerContents <- c(movie10ReviewerContents, scrape(session) %>% html_nodes('div.text.show-more__control') %>% html_text())
  movie10Ratings <- c(movie10Ratings, scrape(session) %>% html_nodes('span.rating-other-user-rating') %>% html_text())
  
  # Extract pagination key for the next page
  pagination_key <- scrape(session) %>% html_nodes("div.load-more-data") %>% html_attr("data-key")
  
  # Check if we have reached the desired number of reviews
  if (length(movie10Usernames) >= reviews_to_scrape) {
    break
  }
}
```

```{r}
# Create a data frame
movie10 <- data.frame(
  Usernames = movie10Usernames[1:300],
  Reviewer_Date = movie10ReviewerDates[1:300],
  Reviewer_Content = movie10ReviewerContents[1:300],
  Rating = movie10Ratings[1:300]
)
```

```{r}
# Save as CSV
write.csv(movie10, file = "movie10.csv", row.names = FALSE)
```

```{r}
# Print the data frame
print(movie10)

```